import type {TCategory} from '@/models'

export const category: TCategory[] = [
  {type: 'favorite', name: 'Favoris'},
  {type: 'fast', name: 'Rapides'},
  {type: 'easy', name: 'Faciles'},
  {type: 'dessert', name: 'Desserts'},
  {type: 'asian', name: 'Asiatiques'},
  {type: 'light', name: 'IG bas'},
]

export const recipeData = [
  {
    id: '1',
    title: 'Spaghetti Carbonara',
    description: 'Un classique italien à base de pâtes, oeufs et fromage.',
    category: 'favorite',
    ingredients: ['spaghetti', 'oeufs', 'parmesan', 'lardons', 'poivre'],
    steps:
      'Faire cuire les pâtes, mélanger les oeufs et le fromage, ajouter les lardons, mélanger le tout.',
    preparationTime: '00:10',
    cookingTime: '00:15',
    persNb: 4,
  },
  {
    id: '2',
    title: 'Poulet Tikka Masala',
    description: 'Un curry indien épicé et crémeux.',
    category: 'asian',
    ingredients: ['poulet', 'yaourt', 'épices', 'crème', 'tomates'],
    steps: 'Mariner le poulet, cuire avec les épices et la sauce tomate, ajouter la crème.',
    preparationTime: '00:20',
    cookingTime: '00:30',
    persNb: 4,
  },
  {
    id: '3',
    title: 'Salade César',
    description: 'Une salade fraîche avec poulet, croûtons et parmesan.',
    category: 'light',
    ingredients: ['laitue', 'poulet', 'parmesan', 'croûtons', 'sauce César'],
    steps: 'Préparer les ingrédients, mélanger avec la sauce.',
    preparationTime: '00:15',
    persNb: 2,
  },
  {
    id: '4',
    title: 'Quiche Lorraine',
    description: 'Une tarte salée traditionnelle française.',
    category: 'easy',
    ingredients: ['pâte brisée', 'lardons', 'crème', 'oeufs', 'fromage râpé'],
    steps: 'Étaler la pâte, ajouter la garniture, cuire au four.',
    preparationTime: '00:15',
    cookingTime: '00:30',
    persNb: 6,
  },
  {
    id: '5',
    title: 'Brownies au chocolat',
    description: 'Dessert gourmand et chocolaté.',
    category: 'dessert',
    ingredients: ['chocolat', 'beurre', 'sucre', 'oeufs', 'farine'],
    steps: 'Faire fondre le chocolat, mélanger avec les autres ingrédients, cuire au four.',
    preparationTime: '00:10',
    cookingTime: '00:20',
    persNb: 8,
  },
  {
    id: '6',
    title: 'Sushi',
    description: 'Rouleaux japonais de riz et poisson.',
    category: 'asian',
    ingredients: ['riz à sushi', 'nori', 'saumon', 'avocat', 'wasabi'],
    steps: 'Préparer le riz, assembler les sushis, rouler et découper.',
    preparationTime: '00:30',
    persNb: 4,
  },
  {
    id: '7',
    title: 'Soupe de potiron',
    description: 'Une soupe crémeuse et réconfortante.',
    category: 'light',
    ingredients: ['potiron', 'oignon', 'crème', 'bouillon', 'épices'],
    steps: 'Cuire les légumes, mixer avec la crème et le bouillon.',
    preparationTime: '00:15',
    cookingTime: '00:20',
    persNb: 4,
  },
  {
    id: '8',
    title: 'Ratatouille',
    description: 'Un mélange de légumes méditerranéens.',
    category: 'favorite',
    ingredients: ['aubergine', 'courgette', 'poivron', 'tomates', 'oignon'],
    steps: "Couper les légumes, cuire à feu doux avec de l'huile d'olive.",
    preparationTime: '00:20',
    cookingTime: '00:40',
    persNb: 6,
  },
  {
    id: '9',
    title: 'Crêpes',
    description: 'Une recette de base pour des crêpes légères.',
    category: 'dessert',
    ingredients: ['farine', 'oeufs', 'lait', 'sucre', 'beurre'],
    steps: 'Mélanger les ingrédients, cuire dans une poêle chaude.',
    preparationTime: '00:10',
    cookingTime: '00:20',
    persNb: 4,
  },
  {
    id: '10',
    title: 'Guacamole',
    description: "Une sauce mexicaine à base d'avocats.",
    category: 'fast',
    ingredients: ['avocats', 'citron vert', 'tomate', 'oignon', 'coriandre'],
    steps: 'Écraser les avocats, mélanger avec les autres ingrédients.',
    preparationTime: '00:10',
    persNb: 4,
  },
]
