import type {TCategory} from '@/models'

export const category: TCategory[] = [
  {type: 'favorite', name: 'Favoris'},
  {type: 'fast', name: 'Rapides'},
  {type: 'easy', name: 'Faciles'},
  {type: 'dessert', name: 'Desserts'},
  {type: 'asian', name: 'Asiatiques'},
  {type: 'light', name: 'IG bas'},
]

export const recipeExample = {
  title: 'Kimchi',
  category: 'asian',
  description: 'Du chou fermenté épicé coréen',

  steps: [
    'Couper le choix à la base et séparant de délicatement sans déchirer les feuilles',
    "Enlever la base et couper des bouts d'environ environ 5cm",
    'Saler abondamment, et laisser reposer au moins 12h mélanger au fur et à mesure',
    'Détailler les carottes et le blanc en julienne',
    'Couper la base des oignons nouveaux et les réserver pour la pâte de piment',
    'Pour la pate de piment :  mixer le piment, le gingembre, l’ail, la base des oignon nouveau, la poire, une cuillère à soupe de sauce huître et une cuillère à soupe de sauce poisson',
    'Rincer abondamment le choux ',
    'Mélanger le choux les légumes et la pate de piment',
    'Mettre dans un bocal hermétique et laisser fermenter pendant une semaine',
  ],
  ingredients: [
    'piment gochugaru (50gr)',
    'ail',
    'gingembre',
    'carotte',
    'cebette',
    'radis blanc',
    'sauce poisson',
    'sauce huitre',
    'poire bien mûre',
    'choux chinois',
  ],
  preparationTime: '13:00',
}

export const recipeExample2 = {
  title: 'Cookie sans gluten',
  description: 'Une délicieuse recette de cookies sans gluten',
  category: 'light',
  steps: [
    'Faire préchauffer le four à 180°',
    "Faire fondre le beurre et l'huile de coco à feu doux fouettez puis rajoutez le sucre",
    "Enfin rajoutez dans la casserole l'œuf et fouetter à nouveau.",
    'Ajoutez petit à petit les farines et la poudre de cacao. ',
    'Rajoutez les morceaux de chocolat pâtissiers. ',
    'Avec une grande cuillère faite des petits tas sur un papier sulfurisé puis écraser- les avec le dos de la cuillère pour former les cookies.',
    'Enfournez à 180° pendant environ 5 min .',
  ],
  ingredients: [
    '50 g de farine de pois chiche',
    '150g de farine Maïzena',
    '50g beurre demi-sel',
    "80g d'huile de coco",
    '100g de sucre glace',
    '1 oeuf',
    'De la poudre de pur cacao',
    'Morceau de chocolat pâtissier 70%',
  ],
  preparationTime: '00:20',
  cookingTime: '00:5',
}

export const recipeData = [
  {
    id: 'spaghetti-carbonara',
    title: 'Spaghetti Carbonara',
    description: 'Un classique italien à base de pâtes, oeufs et fromage.',
    category: 'favorite',
    ingredients: ['spaghetti', 'oeufs', 'parmesan', 'lardons', 'poivre'],
    steps: [
      'Faire cuire les pâtes',
      ' mélanger les oeufs et le fromage',
      ' ajouter les lardons, mélanger le tout.',
    ],
    preparationTime: '00:10',
    cookingTime: '00:15',
    persNb: 4,
  },
  {
    id: 'poulet-tikka-masala',
    title: 'Poulet Tikka Masala',
    description: 'Un curry indien épicé et crémeux.',
    category: 'asian',
    ingredients: ['poulet', 'yaourt', 'épices', 'crème', 'tomates'],
    steps: ['Mariner le poulet', ' cuire avec les épices et la sauce tomate', ' ajouter la crème.'],
    preparationTime: '00:20',
    cookingTime: '00:30',
    persNb: 4,
  },
  {
    id: 'salade-cesar',
    title: 'Salade César',
    description: 'Une salade fraîche avec poulet, croûtons et parmesan.',
    category: 'light',
    ingredients: ['laitue', 'poulet', 'parmesan', 'croûtons', 'sauce César'],
    steps: ['Préparer les ingrédients', ' mélanger avec la sauce.'],
    preparationTime: '00:15',
    persNb: 2,
  },
  {
    id: 'quiche-lorraine',
    title: 'Quiche Lorraine',
    description: 'Une tarte salée traditionnelle française.',
    category: 'easy',
    ingredients: ['pâte brisée', 'lardons', 'crème', 'oeufs', 'fromage râpé'],
    steps: ['Étaler la pâte', ' ajouter la garniture', ' cuire au four.'],
    preparationTime: '00:15',
    cookingTime: '00:30',
    persNb: 6,
  },
  {
    id: 'brownies-chocolat',
    title: 'Brownies au chocolat',
    description: 'Dessert gourmand et chocolaté.',
    category: 'dessert',
    ingredients: ['chocolat', 'beurre', 'sucre', 'oeufs', 'farine'],
    steps: ['Faire fondre le chocolat', ' mélanger avec les autres ingrédients', ' cuire au four.'],
    preparationTime: '00:10',
    cookingTime: '00:20',
    persNb: 8,
  },
  {
    id: 'sushi',
    title: 'Sushi',
    description: 'Rouleaux japonais de riz et poisson.',
    category: 'asian',
    ingredients: ['riz à sushi', 'nori', 'saumon', 'avocat', 'wasabi'],
    steps: ['Préparer le riz', ' assembler les sushis', ' rouler et découper.'],
    preparationTime: '00:30',
    persNb: 4,
  },
  {
    id: 'soupe-potiron',
    title: 'Soupe de potiron',
    description: 'Une soupe crémeuse et réconfortante.',
    category: 'light',
    ingredients: ['potiron', 'oignon', 'crème', 'bouillon', 'épices'],
    steps: ['Cuire les légumes', ' mixer avec la crème et le bouillon.'],
    preparationTime: '00:15',
    cookingTime: '00:20',
    persNb: 4,
  },
  {
    id: 'ratatouille',
    title: 'Ratatouille',
    description: 'Un mélange de légumes méditerranéens.',
    category: 'favorite',
    ingredients: ['aubergine', 'courgette', 'poivron', 'tomates', 'oignon'],
    steps: ['Couper les légumes', " cuire à feu doux avec de l'huile d'olive."],
    preparationTime: '00:20',
    cookingTime: '00:40',
    persNb: 6,
  },
  {
    id: 'crepes',
    title: 'Crêpes',
    description: 'Une recette de base pour des crêpes légères.',
    category: 'dessert',
    ingredients: ['farine', 'oeufs', 'lait', 'sucre', 'beurre'],
    steps: ['Mélanger les ingrédients', ' cuire dans une poêle chaude.'],
    preparationTime: '00:10',
    cookingTime: '00:20',
    persNb: 4,
  },
  {
    id: 'guacamole',
    title: 'Guacamole',
    description: "Une sauce mexicaine à base d'avocats.",
    category: 'fast',
    ingredients: ['avocats', 'citron vert', 'tomate', 'oignon', 'coriandre'],
    steps: ['Écraser les avocats', ' Mélanger avec les autres ingrédients.'],
    preparationTime: '00:10',
    persNb: 4,
  },
]
